[package]
name = "mylog/driftlegends"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
knit = "sleitnick/knit@1.5.1"
signal = "sleitnick/signal@1.5.0"
component = "sleitnick/component@2.4.6"
trove = "sleitnick/trove@0.5.0"
task-queue = "sleitnick/task-queue@0.1.1"
table-util = "sleitnick/table-util@1.2.0"
log = "sleitnick/log@0.1.1"
enum-list = "sleitnick/enum-list@2.0.1"
suphisdatastoremodule = "nametakenbonk/suphisdatastoremodule@1.2.0"
concur = "sleitnick/concur@0.1.2"
